fix / notification 43 무한 스크롤 lastId 값 변경
slamapp/server pull request #44
Opened 2022-05-15 21:43 UTC by locodingve

2022-05-16 00:01 UTC, manudeli commented on src/main/java/org/slams/server/notification/service/NotificationService.java
> +    public Long findNotificationLastId(CursorPageRequest cursorRequest, int dataSize){
Long 맞나요? 질문주신거에서 궁금해서 알림들은 id가 uuid로 오고 있어서요 혹시나해서 남겨요~

2022-05-17 12:15 UTC, KwonYeKyeong requested changes
안녕하세요 플로라😊😊 젤리입니다. 오랜만에 코드리뷰하네요~

2022-05-17 12:15 UTC, KwonYeKyeong commented on src/main/java/org/slams/server/notification/controller/NotificationController.java
>          ));
response안에 담길 content와 lastId 값을 service에서 한번에 받아와서 만들어주는게 가독성이 더 좋을 것 같아요~

2022-05-17 12:15 UTC, KwonYeKyeong commented on src/main/java/org/slams/server/notification/service/NotificationService.java
>      public List<Notification> cursorPageForFindAllByUserId(Long userId, CursorPageRequest cursorRequest){
이 메소드는 service단에서만 사용되네요. private으로 선언하는 게 좋을 것 같아요ㅎㅎ

2022-05-17 12:15 UTC, KwonYeKyeong commented on src/main/java/org/slams/server/notification/service/NotificationService.java
>      }
제가 이해한 바로는 추후에 프론트에서 pageId값을 받아오자는 건가요??
그리고 `cursorReqeust.getLastId()`값이 Long타입이라 `Integer`로 바꿔줬을 때 **범위를 벗어날 위험이 있어보입니다.**

2022-05-17 12:15 UTC, KwonYeKyeong commented on src/main/java/org/slams/server/notification/service/NotificationService.java
>          }
else를 충분히 줄일 수 있을 것 같아요~ 117번째 else 삭제, 124번째 else 삭제가 가능해보입니다. 블록을 줄여야 가독성이 더 높아질 것 같아요~

2022-05-18 12:59 UTC, locodingve commented
@KwonYeKyeong 젤리~ 감사해요~ 그런데 본 코드는 전부 수정 될 것 같아요~ 피드백 감사합니다~ 👍🏻🙏🏻

2022-05-21 10:48 UTC, locodingve commented on src/main/java/org/slams/server/notification/service/NotificationService.java
>      public List<Notification> cursorPageForFindAllByUserId(Long userId, CursorPageRequest cursorRequest){
넵~

2022-06-02 03:34 UTC, merged